Enterprise - Assignment3/Enterprise - Assignment3/Controllers/InvoiceController.cs
using Assignment4.Domain.Persistence;
using Enterprise___Assignment3.Domain.Entities;
using Enterprise___Assignment3.Domain.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enterprise___Assignment3.Controllers
{
    public class InvoiceController : Controller
    {
        private const string INVOICE_SESSION_OBJ = "Invoices";
        private const string USER_SESSION_OBJ = "USER";

        public InvoiceStorage InvoiceStorage
        {
            get
            {
                InvoiceStorage invoices = Session[INVOICE_SESSION_OBJ] as InvoiceStorage;
                if (invoices == null)
                {
                    invoices = new InvoiceStorage();
                    Session[INVOICE_SESSION_OBJ] = invoices;
                }
                return invoices;
            }
        }
        

        public User User
        {
            get
            {
                User user = Session[USER_SESSION_OBJ] as User;
                if (user == null)
                {
                    user = new User();
                    Session[USER_SESSION_OBJ] = user;
                }
                return user;
            }
        }
        private IInvoiceRepository _invoiceRepo;
        public InvoiceController(IInvoiceRepository invoiceRepo)
        {
            _invoiceRepo = invoiceRepo;
        }
        public ActionResult Delegater(string submit)
        {
            if (submit.Equals("Manage "))
            {
                return View("UserView", "UserAccounts",User);
            }
            else if (submit.Equals("Add Invoice"))
            {
                return View("AddInvoice");
            }
            else if (submit.Equals("Review Recievables"))
            {
                return View("ReviewRecievables", _invoiceRepo.InvoiceList);
            }
            else if (submit.Equals("Manage Invoices"))
            {
                return View("ManageInvoices", _invoiceRepo.InvoiceList);
            }
            else if (submit.Equals("Back"))
            {
                return View("../UserAccounts/UserView", User);
            }
            return View();
        }
        // GET: Invoice
        public ActionResult AddInvoice(Invoice invoice,string submit)
        {
            if (submit.Equals("Back"))
            {
                return View("../UserAccounts/UserView", User);
            }
            else if (submit.Equals("Add Invoice")) 
            {
                _invoiceRepo.AddInvoice(invoice);
            }
            else if (submit.Equals("Save Invoice"))
            {
                _invoiceRepo.UpdateInvoice(invoice);
            }
            return View();
        }
        public ActionResult ReviewRecievables()
        {
            return View(InvoiceStorage);
        }
        public ActionResult ManageInvoices()
        {
            return View(InvoiceStorage);
        }
        public ActionResult EditInvoice(Invoice invoice)
        {
            return View("AddInvoice",invoice);
        }
        public ActionResult PayInvoice(Invoice invoice)
        {
            _invoiceRepo.PayInvoice(invoice);
            return View("ManageInvoices", _invoiceRepo.InvoiceList);
        }
    }
}

Enterprise - Assignment3/Enterprise - Assignment3/Controllers/UserAccountsController.cs
using Enterprise___Assignment3.Domain.Entities;
using Enterprise___Assignment3.Domain.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enterprise___Assignment3.Controllers
{
    public class UserAccountsController : Controller
    {  
        private const string USER_SESSION_OBJ = "USER";
        IUserRepository _userAccounts;
        public User User
        {
            get
            {
                User user = Session[USER_SESSION_OBJ] as User;
                if (user == null)
                {
                    user = new User();
                    Session[USER_SESSION_OBJ] = user;
                }
                return user;
            }            
        }
        // GET: UserAccounts
        public UserAccountsController(IUserRepository userAccounts)
        {
            _userAccounts = userAccounts;
        }
        [HttpGet]
        public ActionResult Index()
        {
            IUserRepository userl;
            
            return View();
        }
        [HttpPost]
        public ViewResult Index(User user, string submit)
        {
            User u = _userAccounts.FindUser(user);
            if(u == null)
            {
                ViewBag.FailedLogin = "Username or Password Incorrect Please try again";
                return View();
            }
            else
            {
                Session[USER_SESSION_OBJ] = u;
                return View("UserView", u);
            }
            return View();
        }
    }
}

Enterprise - Assignment3/Enterprise - Assignment3/Views/Invoice/AddInvoice.cshtml
@model Enterprise___Assignment3.Domain.Entities.Invoice
@using Enterprise___Assignment3.Domain.Entities
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>LoginForm</title>
    <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  });
  $(function () {
      $("#datepicker1").datepicker();
  });
    </script>
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>Create Invoice</h4></div>
        <div class="panel-body" style="width:500px; margin:auto">

            @using (Html.BeginForm("AddInvoice", "Invoice"))
            {
                @Html.ValidationSummary()
                if (@Model != null)
                {
                    <div class="form-group">
                        <label>Client Name:</label>
                       
                        @Html.TextBoxFor(x => x.InvoiceNumber, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                }

                <div class="form-group">
                    <label>Client Name:</label>
                    @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Client Address:</label>
                    @Html.TextBoxFor(x => x.ClientAddress, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Date of Shipment:</label>
                    @Html.TextBoxFor(x => x.DateofShipment, new { @class = "form-control", @id = "datepicker" })
                </div>

                <div class="form-group">
                    <label>Payment Due Date:</label>
                    @Html.TextBoxFor(x => x.PaymentDueDate, new { @class = "form-control", @id = "datepicker1" })
                </div>

                <div class="form-group">
                    <label>Product Name:</label>
                    @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Currency?</label>
                    @Html.DropDownListFor(x => x.Currency, new[] {
            new SelectListItem() {Text = "CAD",
            Value = Currency.CAD.ToString()},
            new SelectListItem() {Text = "US",Value = Currency.US.ToString()},
            new SelectListItem() {Text = "EUR",Value = Currency.EUR.ToString()},
             }, "Choose an option", new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Unit Price:</label>
                    @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Product Quantity:</label>
                    @Html.TextBoxFor(x => x.ProductQuantity, new { @class = "form-control" })
                </div>
                <div class="text-center">
                    @if (@Model != null)
                {
                        <h3>Subtotal = @Model.TotalPrice()</h3>
                        <h3>Tax = @{double t = Model.TotalPrice() * .1;}@t</h3>
                        <h3>Total =@{double Total = (Model.TotalPrice() + (Model.TotalPrice()*0.1));} @Total </h3>
                        <h3>Subtotal = @Model.TotalPrice()</h3>
                        <input class="btn btn-success" type="submit" name="submit"
                               value="Save Invoice" />
                            }
                            else
                            {

                                <input class="btn btn-success" type="submit" name="submit"
                                       value="Add Invoice" />
                            }


                    <input class="btn btn-success" type="submit" name="submit"
                           value="Back" />
                </div>

                            }
        </div>
    </div>
</body>

</html>

Enterprise - Assignment3/Enterprise - Assignment3/Views/Invoice/ManageInvoices.cshtml
@model IEnumerable<Invoice>
@using Enterprise___Assignment3.Domain.Entities
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>LoginForm</title>
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>Review Recievables</h4></div>
        <div class="panel-body" style="width:500px; margin:auto">

            <table class="table table-striped">
                <tr>
                    <th>Invoice Number</th>
                    <th>Client Name</th>
                    <th>Total</th>
                    <th>Payment Due Date</th>
                </tr>
                @{double i = 0; }
                @foreach (Invoice invoice in Model)
                {
                    if (invoice.IsPaid)
                    {

                    }
                    else
                    {
                        string t = invoice.InvoiceNumber.ToString();
                        <tr>
                            <td>@Html.ActionLink(t, "EditInvoice", "Invoice", invoice, null)</td>
                            <td>@invoice.ClientName</td>
                            <td>$@invoice.TotalPrice()</td>
                            <td>@invoice.PaymentDueDate</td>
                            <td>@Html.ActionLink("Paid", "PayInvoice", "Invoice", invoice, null)</td>
                        </tr>
                        i = i + invoice.TotalPrice();
                    }

                }
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Sum</td>
                        <td>$@i</td>
                    </tr>
                </tfoot>
            </table>
            @using (Html.BeginForm("Delegater", "Invoice"))
            {
                <div class="text-center">
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Add Invoice" />
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Back" />
                </div>
            }
        </div>
    </div>
</body>

</html>


Enterprise - Assignment3/Enterprise - Assignment3/Views/Invoice/ReviewRecievables.cshtml
@model IEnumerable<Invoice>
@using Enterprise___Assignment3.Domain.Entities
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>LoginForm</title>
    <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  });
  $(function () {
      $("#datepicker1").datepicker();
  });
    </script>
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>Review Recievables</h4></div>
        <div class="panel-body" style="width:500px; margin:auto">

            <table class="table table-striped">
                <tr>
                    <th>Invoice Number</th>
                    <th>Client Name</th>
                    <th>Total</th>
                    <th>Payment Due Date</th>
                </tr>
                @{double i = 0; }
                @foreach (Invoice invoice in Model)
                {
                    if (invoice.IsPaid)
                    {

                    }
                    else
                    {
                        <tr>
                            <td>@invoice.InvoiceNumber</td>
                            <td>@invoice.ClientName</td>
                            <td>$@invoice.TotalPrice()</td>
                            <td>@invoice.PaymentDueDate</td>
                        </tr>
                        i += invoice.TotalPrice();
                    }

                }
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Sum</td>
                        <td>$@i</td>
                    </tr>
                </tfoot>
            </table>
            @using (Html.BeginForm("Delegater", "Invoice"))
            {
                <div class="text-center">
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Add Invoice" />
                </div>
            }
        </div>
    </div>
</body>

</html>


Enterprise - Assignment3/Enterprise - Assignment3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Enterprise - Assignment3/Enterprise - Assignment3/Views/UserAccounts/Index.cshtml
@model Enterprise___Assignment3.Domain.Entities.User
@using Enterprise___Assignment3.Domain
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>LoginForm</title>
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>User Login</h4></div>
        <div class="panel-body" style="width:500px; margin:auto" >
          <h4 style="color:red">@Html.Raw(ViewBag.FailedLogin)</h4>
            
            @using (Html.BeginForm("Index","UserAccounts"))
            {
                @Html.ValidationSummary()
                <div class="form-group">
                    <label>Username:</label>
                    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Password:</label>
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Manager Login" />
                    <input class="btn btn-success" type="submit" name="submit"
                           value="User Login" />
                </div>
            }
        </div>
    </div>
</body>
</html>

Enterprise - Assignment3/Enterprise - Assignment3/Views/UserAccounts/ManagerView.cshtml
@model Enterprise___Assignment3.Domain.Entities.User

@{
    ViewBag.Title = "ManagerView";
}

<h2>ManagerView</h2>


Enterprise - Assignment3/Enterprise - Assignment3/Views/UserAccounts/UserView.cshtml
@model Enterprise___Assignment3.Domain.Entities.User
@using Enterprise___Assignment3.Domain.Entities
@{
    ViewBag.Title = "UserView";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>LoginForm</title>
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>@Model.UserType Login</h4></div>
        <div class="panel-body" style="width:500px; margin:auto">

            @using (Html.BeginForm("Delegater", "Invoice"))
            {
                <div class="text-center">
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Add Invoice"/>
                    @if(Model.UserType == AuthorizationType.Manager){
                    <input class="btn btn-success" type="submit" name="submit"
                           value="Review Recievables" />
                        <input class="btn btn-success" type="submit" name="submit"
                               value="Manage Invoices" />
                    }
                </div>
            }
        </div>
    </div>
</body>
</html>
